// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJSoBPt_9BaIjl_Igew4xm5ZN-rW4kkJY',
    appId: '1:107358446244:web:de638a9944e1643c193c31',
    messagingSenderId: '107358446244',
    projectId: 'wastemanagement-ac9bc',
    authDomain: 'wastemanagement-ac9bc.firebaseapp.com',
    storageBucket: 'wastemanagement-ac9bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Vm3_djvUkgyXRN0zCbO0bNhxhAZncvc',
    appId: '1:107358446244:android:b783ad6f111c4039193c31',
    messagingSenderId: '107358446244',
    projectId: 'wastemanagement-ac9bc',
    storageBucket: 'wastemanagement-ac9bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4NtUpdL0oxdF4Dghep9jiXOAHGCHY5AY',
    appId: '1:107358446244:ios:63ab1531e6096faf193c31',
    messagingSenderId: '107358446244',
    projectId: 'wastemanagement-ac9bc',
    storageBucket: 'wastemanagement-ac9bc.firebasestorage.app',
    iosBundleId: 'com.example.wasteManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4NtUpdL0oxdF4Dghep9jiXOAHGCHY5AY',
    appId: '1:107358446244:ios:63ab1531e6096faf193c31',
    messagingSenderId: '107358446244',
    projectId: 'wastemanagement-ac9bc',
    storageBucket: 'wastemanagement-ac9bc.firebasestorage.app',
    iosBundleId: 'com.example.wasteManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJSoBPt_9BaIjl_Igew4xm5ZN-rW4kkJY',
    appId: '1:107358446244:web:6a89db07e48a638d193c31',
    messagingSenderId: '107358446244',
    projectId: 'wastemanagement-ac9bc',
    authDomain: 'wastemanagement-ac9bc.firebaseapp.com',
    storageBucket: 'wastemanagement-ac9bc.firebasestorage.app',
  );
}
